# Generated by Django 4.2.6 on 2023-10-27 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeddingMain',
            fields=[
                ('wedding_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('passwd', models.CharField(max_length=60)),
                ('groom_name', models.CharField(max_length=10)),
                ('groom_father_name', models.CharField(max_length=10, null=True)),
                ('groom_mother_name', models.CharField(max_length=10, null=True)),
                ('bride_name', models.CharField(max_length=10)),
                ('bride_father_name', models.CharField(max_length=10, null=True)),
                ('bride_mother_name', models.CharField(max_length=10, null=True)),
                ('use_guestbook', models.BooleanField(default=False)),
                ('wedding_date', models.DateField(verbose_name='wedding date')),
                ('wedding_time', models.CharField(max_length=20)),
                ('reg_dtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img')),
                ('wedding_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.weddingmain')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groom_phone', models.CharField(max_length=13)),
                ('groom_father_phone', models.CharField(max_length=13, null=True)),
                ('groom_mother_phone', models.CharField(max_length=13, null=True)),
                ('bride_phone', models.CharField(max_length=13)),
                ('bride_father_phone', models.CharField(max_length=13, null=True)),
                ('bride_mother_phone', models.CharField(max_length=13, null=True)),
                ('wedding_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.weddingmain')),
            ],
        ),
        migrations.CreateModel(
            name='GuestBook',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('passwd', models.CharField(max_length=60)),
                ('reg_dtime', models.DateTimeField(auto_now_add=True)),
                ('wedding_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.weddingmain')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('address_tel', models.CharField(max_length=100, null=True)),
                ('wedding_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.weddingmain')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groom_account', models.CharField(max_length=30)),
                ('groom_father_account', models.CharField(max_length=30, null=True)),
                ('bride_account', models.CharField(max_length=30)),
                ('bride_father_account', models.CharField(max_length=30, null=True)),
                ('wedding_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.weddingmain')),
            ],
        ),
    ]
