# Generated by Django 4.2.6 on 2023-10-27 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestbook',
            name='wedding_id',
            field=models.CharField(max_length=20),
        ),
    ]
