# Generated by Django 4.2.6 on 2023-10-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_guestbook_wedding_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestbook',
            name='message',
            field=models.CharField(default='', max_length=500),
        ),
    ]
