# Generated by Django 4.2.6 on 2023-10-31 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_guestbook_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='kakaomap_key',
            field=models.CharField(default=1698729543108, max_length=10),
            preserve_default=False,
        ),
    ]
