# Generated by Django 4.2.6 on 2023-10-31 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_address_kakaomap_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='kakaomap_timestamp',
            field=models.IntegerField(default=1698729543108),
            preserve_default=False,
        ),
    ]
